apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/fakiletemmytope/argocd-test-manifests.git
    targetRevision: HEAD
    path: ./declarative-argocd/app-of-app/apps/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
